run:
  timeout: 5m

output:
  formats:
    - format: colored-line-number   

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - ineffassign
    - staticcheck
    - unused
    - gofumpt

linters-settings:
  gofumpt:
    extra-rules: true
